version: "3.7"

services:
  web:
    restart: always
    build: 
        context: "."
    ports:
        - 8000:80 
    environment:
        ConnectionStrings__HangfireConnection: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
        ASPNETCORE_ENVIRONMENT: Development # remove this in case of production
    networks:
      - mynetwork
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # if "trust" is not set, the error message is something like
      # "Error: Database is uninitialized and superuser password is not specified."
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data
      # the :- tells docker-compose to use the given default value (here: 5432)
      # if the environment variable is empty or not defined
      # More information are listed in the docker-compose documentation:
      # https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files
      PG_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - mynetwork
volumes:
  db-data:
networks:
  mynetwork:
    driver: bridge