name: build and test

on:
  push:
    branches:
      - "*"

env:
  DOTNET_VERSION: "7.0.201" # The .NET SDK version to use
  working-directory: ./

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
